### ISSUE TITLE
Bug: Query string from another scope triggers error

### ISSUE THREAD

**Issue by adrianhelvik** [AntonNiklasson/eslint-plugin-knex#1]
There is a bug when the string used for queries are located in another scope.

```
const END_TIME_QUERY = `now() + interval '123 seconds'`

export default async function updateEndTime() {
  await await db('foo').update({
    ends_at: knex.raw(END_TIME_QUERY),
  })
}
```

This triggers an error in eslint-plugin-knex/rules/avoid-injections.js:44:56

```    const queryVariableDefinition = context
      .getScope(queryNode)
      .variables.find((v) => v.name === queryNode.name).defs[0].node;
                                                         // ^ Here

```

**Comment by adrianhelvik** [comment]
I think an error would be okay, as this requires extra attention. But this bug makes it impossible to suppress the error.

**Comment by AntonNiklasson** [comment]
Thanks for reporting this! I'll have a look.

**Comment by AntonNiklasson** [comment]
@adrianhelvik A patch for this is live in v0.1.2. Thanks again for the report 😊
